import './globals.css'
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import { Providers } from './providers/Providers'
import { ReduxProviders } from '@/Redux/Provider';
import { NextAuthProvider } from './nextAuthProvider';

const poppins = Poppins({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
        <ReduxProviders>
          <NextAuthProvider>
            {children}
          </NextAuthProvider>
        </ReduxProviders>
      </body>
    </html>
  )
}
